### ISSUE TITLE
Repo stats don't show until reload

### ISSUE THREAD

**Issue by sf-old** [rendrjs/rendr-app-template#1]
Haven't had a chance to look in to this further but at least on my local machine the repo stats/show page doesn't show the statistics until you reload the page.

Via Navigating: http://cl.ly/image/1i2C3m3R3B3w
After Reload: http://cl.ly/image/2t3T3f0y3c1P

I'm running node v0.10.2 on Mountain Lion.

**Comment by spikebrehm** [comment]
Thanks for the report! I've seen that as well -- it's because the representation of 'repo' in the GitHub API is different between the different API responses.  We actually ran into that when we originally built Rendr, so there's an [`ensureKeys`](https://github.com/airbnb/rendr/blob/master/shared/fetcher.coffee#L120) option you can pass to `this.app.fetch` to force it to re-fetch the resource instead of using the cached representation.  I'll add this to the example!

**Comment by spikebrehm** [comment]
Here's how you would do that! Check it: https://github.com/airbnb/rendr-app-template/commit/79d5b018f259a21241ed5f015bb067f8d2a5ef57
